# Travis CI configuration file
language: java

jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7
  - openjdk6

before_script:
  - mvn -f 2Sum/Java/pom.xml clean install -DskipTests=true
  - mvn -f QuickSort/Java/pom.xml clean install -DskipTests=true
  - mvn -f MergeSort/Java/pom.xml clean install -DskipTests=true
  - mvn -f InversionsCount/Java/pom.xml clean install -DskipTests=true
  - mvn -f MedianMaintenance/Java/pom.xml clean install -DskipTests=true
  - mvn -f PrimMST/Java/pom.xml clean install -DskipTests=true


script:
  - mvn -f 2Sum/Java/pom.xml test
  - mvn -f QuickSort/Java/pom.xml test
  - mvn -f MergeSort/Java/pom.xml test
  - mvn -f InversionsCount/Java/pom.xml test
  - mvn -f MedianMaintenance/Java/pom.xml test
  - mvn -f PrimMST/Java/pom.xml test

